### ISSUE TITLE
Batch size in the annotation interface

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#10]
Currently, the batch size is set to 100 (in the annotation tool): https://github.com/Living-with-machines/MapReader/blob/main/mapreader/annotate/utils.py#L155

Add this option to `prepare_annotation` (https://github.com/Living-with-machines/MapReader/blob/main/mapreader/annotate/utils.py#L239) so that the user can change the batch size if needed.

**Comment by rwood-97** [comment]
Fixed by new annotation interface
