### ISSUE TITLE
FAQ/troubleshooting addition

### ISSUE THREAD

**Issue by kallewesterling** [Living-with-machines/MapReader#106]
**Is your documentation update related to a problem? Please describe.**
Sometimes when installing on a macOS with M1 architecture, this error can occur:
<img width="1108" alt="Screenshot 2023-03-14 at 06 56 16" src="https://user-images.githubusercontent.com/7298727/224920152-f89eeba5-c35b-4bfa-bc50-a843251bc8b8.png">

**Describe the solution you'd like**
Perhaps we could add a FAQ/troubleshooting section in the documentation, with errors that we've encountered and pointing out how to best solve them.

**Describe alternatives you've considered**
In this case, I found that the instructions in [this StackOverflow](https://stackoverflow.com/questions/65825346/pip-install-pandas-results-in-error-python3-8-pycharm-apple-silicon) helped. Essentially, it only needs two more steps:

```sh
$ brew install openblas
```

Followed by:

```sh
$ OPENBLAS="$(brew --prefix openblas)" pip install mapreader
```

**Comment by rwood-97** [comment]
Addressed by PR #133
