### ISSUE TITLE
mention cartopy to view UK borders

### ISSUE THREAD

**Issue by kasparvonbeelen** [Living-with-machines/MapReader#107]
**Is your documentation update related to a problem? Please describe.**

Not a problem, just a small additional note.

**Describe the solution you'd like**

To render the contours of the UK, with `plot_metadata_on_map` you need to install `cartopy` otherwise you only see the contours of each map.

**Additional context**

This refers to the output of `my_ts.plot_metadata_on_map(add_text=True)`

**Comment by rwood-97** [comment]
will be fixed after geotiff update (with updated setup.py) 
See PR #79
