### ISSUE TITLE
Tiny typo in TileServer

### ISSUE THREAD

**Issue by kasparvonbeelen** [Living-with-machines/MapReader#111]
**Describe the bug**

When intitializing the `TileServer' print contains a tiny typo

**To Reproduce**

Running this code 
```python
from mapreader import TileServer
my_ts = TileServer(metadata_path="./MapReader/worked_examples/persistent_data/metadata_OS_One_Inch_GB_WFS_light.json", 
                   download_url="mapseries-tilesets.your_URL_here/{z}/{x}/{y}.png")
```

Prints:

```
Metada file has 480 items.
Download URL: mapseries-tilesets.your_URL_here/{z}/{x}/{y}.png
Geometry: polygone
```
**Expected behavior**

Typo in `metada` and `polygone`.
```
Metadata file has 480 items.
Download URL: mapseries-tilesets.your_URL_here/{z}/{x}/{y}.png
Geometry: polygon
```

**Screenshots**

<img width="1117" alt="Screenshot 2023-03-14 at 11 17 14" src="https://user-images.githubusercontent.com/11618160/224985007-542e893e-0d20-43c9-8de8-b3ee1233c241.png">

**Comment by kallewesterling** [comment]
Pending PR https://github.com/Living-with-machines/MapReader/pull/151
