### ISSUE TITLE
Clarify how to set the path to local input files

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#121]
**Is your documentation update related to a problem? Please 

From the workshop notes:
> Is there a need for some instructions on where to put your own files locally? Changing the path
> How to change the path? Could we have a dialogue in the notebook that asks you where to put them locally? (And in this case print the filepath so you can then paste it into your cells) 👍

**Comment by dcsw2** [comment]
A related comment for documentation:

`Can we make sure copy-paste examples are distinct from ‘your/path/here’ examples where you are required to change something in the code`
