### ISSUE TITLE
Visualization colormap is inconsistant with the example in the documentation

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#123]
**Is your documentation update related to a problem? Please describe.**

from the workshop notes:

> Visualization (at the bottom of Load & Patchify section): The colormap I get when running the my_files.show_par(parent_list[0], value=value, vmin=vmin, vmax=vmax) examples is not the same as in the User Guide. It can be changed using the parameter colorbar (e.g. colorbar='viridis') in the call of show_par(). However, I think for consistency this parameter should be called colormap instead of colorbar.
Following up on previous comment for show_par(), I would definitely make a note about colorbar in the documentation.

**Comment by rwood-97** [comment]
Fixed by PR #79

**Comment by rwood-97** [comment]
fixed in main
