### ISSUE TITLE
Annotation interface does not work in Jupyter in Firefox

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#128]
**Describe the bug**

**To Reproduce**

To be completed:

1. Open an annotation notebook in jupyter in firefox
2. Prepare annotations

```
annotation=prepare_annotation(userID, 
					task,
 					annotation_tasks_file,
					annotation_set=annotation_set)
```

3. Attempt to display the annotation interface:

```
annotation
```

```
Model class 'AnnotationModel' from module 'ipyannotate' is loaded but can not be instantiated
_make_model@http://localhost:8889/nbextensions/jupyter-js-widgets/extension.js:2:747339
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by rwood-97** [comment]
See issues #113 and #114
