### ISSUE TITLE
EOI report contribution March 2023

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#137]
Instructions:
Paste under the relevant heading [_**Legacy planning**_] up to 5 one-sentence bullet points on what they’ve done since January (this can also be used for our quarterly report - win!)

Then, on the day can the person leading the WP talk to those 5 bullet points (perhaps with 1-2 slides if you so desire). Plus a couple of bullet points for:
- What remains to be done to complete that bit of work
- What needs to be dropped or downsized to make that attainable with our remaining time and team. I.e. What is the MVP version of this that meets the project’s aims? You may wish to consult the [Roadmap](https://docs.google.com/spreadsheets/d/1bD_Q6PRBLwK0oRt83LxFJZvnPm9pvX7POhc7Ps_TwRs/edit#gid=0).

**Comment by kmcdono2** [comment]
What have we done since Jan 2023:
1. Create MapReader documentation
2. Align code, README, and docs to simplify use. Minor bug fixes and updates.
3. Plan and host MapReader workshop to stress test code and documentation.
4. Update MapReader SIGSPATIAL data license (now CC-BY) and re-share dataset on NLS Data Foundry.
5. Prioritize work and plan for MapReader launch event on June 7.

@rwood-97 @andrewphilipsmith @dcsw2 @kasparvonbeelen @kallewesterling anything to tweak or add here? 
In particular @rwood-97 and @andrewphilipsmith do you want to highlight any fixes/updates that are especially important?

**Comment by kmcdono2** [comment]
- what remains to be done?

1. Finalize programme for June 7 launch and June 8 smaller group day.
2. Priorities for MapReader functionality prior to June 7 (task sizing in progress). 4 sprints of 2 weeks between now and June 7.
3. Work on minimal input/output viz notebooks with @kallewesterling 


- what needs to be dropped or downsized?
1. Using new BL maps for MapReader experiment
2. ?

@dcsw2 @kasparvonbeelen @rwood-97 @andrewphilipsmith @kallewesterling What have I forgotten, what would you like to add?

**Comment by rwood-97** [comment]
looks good to me
