### ISSUE TITLE
Keep coordinates for patches when sliced

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#138]
**Is your feature request related to a problem? Please describe.**
Patch coordinates are lost upon slicing.

**Describe the solution you'd like**
1. Keep coordinates for patches and save in mapImages dictionary/dataframe

2. Plus:
Option 1 - save patches as geoTIFFs/geoJPEGs with associate geo- metadata
Option 2 - save patches as standard image files (PNG) plus separate geo- metadata file (World file - PWG) which is standard in GIS.

**Describe alternatives you've considered**
Make finding coordinates of patches a post-processing step - see #37

**Comment by kmcdono2** [comment]
Is it looking like patch visual content (either of the options proposed above) will be ready by June 7? Asking so @kallewesterling and I can think about prepping a viz option for this kind of output.

**Comment by rwood-97** [comment]
> Keep coordinates for patches and save in mapImages dictionary/dataframe

This is done (not merged or anything but should be done by June easily).

> Plus:
> Option 1 - save patches as geoTIFFs/geoJPEGs with associate geo- metadata
> Option 2 - save patches as standard image files (PNG) plus separate geo- metadata file (World file - PWG) which is standard in GIS.

This is not done yet but I can start working on it if you would like (feasibly could be done by June).

**Comment by kmcdono2** [comment]
So wonderful. Thanks for the quick update. Yes, if we could do either Option 1 or 2 (maybe whichever is easier?) to start, then we could test next week (or following???) with a mini task and create a dataset we can visualize.

**Comment by rwood-97** [comment]
@kmcdono2 
Here is code for writing geotiff:

```
    def _save_patch_as_geotiff(
        self, 
        patch_id: str, 
        rewrite: Optional[bool] = False, 
        verbose: Optional[bool] = False,
        crs: Optional[str] = None,
    ) -> None:
        """Save a patch as a geotiff.

        Parameters
        ----------
        patch_id : str
            The ID of the patch to write.
        rewrite : bool, optional
            Whether to rewrite files if they already exist, by default False
        verbose : bool, optional
            Whether to print verbose outputs, by default False
        crs : Optional[str], optional
            The CRS of the coordinates.
            If None, the method will first look for ``CRS`` in the patches dictionary and use those. If ``CRS`` cannot be found in the dictionary, the method will use "EPSG:4326".
            By default None.

        Raises
        ------
        ValueError
            If patch directory does not exist.
        """

        patch_path = self.patches[patch_id]["image_path"]
        patch_dir = os.path.dirname(patch_path)

        if not os.path.exists(patch_dir):
            raise ValueError(f'[ERROR] Patch directory "{patch_dir}" does not exist.')
        
        patch_id_no_ext = os.path.splitext(patch_id)[0]
        geotiff_path = f"{patch_dir}/{patch_id_no_ext}.tif"
        
        self.patches[patch_id]["geotiff_path"] = geotiff_path
        
        if os.path.isfile(f"{geotiff_path}"):
            if not rewrite:
                self._print_if_verbose(
                    f'[INFO] File already exists: {geotiff_path}.', verbose
                    )
                return
            
        self._print_if_verbose(
            f"[INFO] Creating: {geotiff_path}.",
            verbose,
        )

        if "shape" not in self.patches[patch_id].keys():
            self._add_shape_id(patch_id)
        height, width, channels = self.patches[patch_id]["shape"]

        if "coordinates" not in self.patches[patch_id].keys():
            self._add_patch_coords_id(patch_id)
        coords = self.patches[patch_id]["coordinates"]
        
        if not crs:
            crs = self.patches[patch_id].get("CRS", "EPSG:4326")

        patch_affine = rasterio.transform.from_bounds(*coords, width, height)
        patch = Image.open(patch_path)
        patch_array = reshape_as_raster(patch)

        with rasterio.open(
            f"{geotiff_path}",
            'w',
            driver="GTiff",
            height=patch.height,
            width=patch.width,
            count=channels,
            transform=patch_affine,
            dtype='uint8',
            nodata=0,
            crs=crs,
        ) as dst:
            dst.write(patch_array)    

```

If you want to try it out:

```
git pull
git switch dev_load
conda create -n mr_test python=3.8
conda activate mr_test
pip install -v -e . 
python -m ipykernel install --user --name mr_test --display-name "mr_test"
```

Then run a notebook and load some files + coordinates (either geotiffs or png + metadata), patchify, then run ``.save_patches_as_geotiffs()`` method your patchified maps.

Can go through this properly in meeting next week if helpful.
