### ISSUE TITLE
establish DOIs for MapReader versions

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#142]
**Is your feature request related to a problem? Please describe.**
Ideally MapReader will be a research object that is citable independent of the paper, esp. once there are new versions. 

**Describe the solution you'd like**
Investigate, but likely publish on zenodo.

- [ ] find examples of repos with DOIs automatically generated for versions @andrewphilipsmith 

**Describe alternatives you've considered**
- Just leaving paper as citable object.
- DOI for the paper and version numbers on PyPI.

**Additional context**
This can be completed after #73

**Comment by kallewesterling** [comment]
There's an automatic feature on Zenodo, which I only now learned about (!!) that can automatically archive the repository and issue a new DOI each time that we'd create a new GitHub release!

See here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by kmcdono2** [comment]
That's great. I'm moving this to the freezer for now, but we can revisit in June/July as we wrap things up.

**Comment by kmcdono2** [comment]
@rwood-97 this is done right?
