### ISSUE TITLE
Update advice for using NLS tileservers

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#144]
**Is your documentation update related to a problem? Please describe.**
Chris Fleet would like to 

From Chris Fleet:
If I had visited the MapReader event you held last week, one thing which I was keen to discuss was whether it would be helpful to expand the existing Tileserver info you have in the documentation at[https://mapreader.readthedocs.io/en/latest/Input-guidance.html](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furl4.mailanyone.net%2Fscanner%3Fm%3D1peg4V-000BGa-54%26d%3D4%257Cmail%252F90%252F1679420400%252F1peg4V-000BGa-54%257Cin4e%257C57e1b682%257C11029744%257C13642207%257C6419ED8FFC201205783AC6220B949AEB%26o%3D%252Fphtu%253A%252Fetse.r0iafl1st.nkcroesptntiooulo.%253Fcokrm%252Fu.o%2525tl%253DAps3hta%2525%25252rFmpF2eeead.radr.dthocsieoFe%25252a%25252lFnIttep2Fns%2525agutcidn-udte.tl%2526ahm05a%253D%25257C10%2525nm7Cudookcr4ghntui%25250%2525cg.Cuk7a.9bfdb47bb06bc8c4534bfb08ba13d29760f435%2525C4e4a955f74b958e1faaf%25258f6Cf9734CC0%25253%2525767080818857507727U5%2525C797onkTn%2525CnwbbWFdZs3pGoJ8eMIjiyWMLC4AAwDwjoJiLVIjiCQLM2lJIiCuz1IBTaIkhi6VLWwIJXCiC%252506MC3D7n%2525%2525030C7C70%2525t%2526%25257%253DdaaCsMbElvMNvRiOGyV1J8Ihdkqv3jTTDXvWcLuwAJVcOr%2525yCsD%2526ew30%253Ddevre%26s%3DuukkMWJgerfAISsMx2fxPLfbx6U&data=05%7C01%7Ckmcdonough%40turing.ac.uk%7C4dd0961b34b14952feac08db2aa7ee83%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638150672992211622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fy1%2FB1C9TGxgyhdFieQGrEtii0ZlFnVA%2BI8O3QE6ExI%3D&reserved=0) to mention how any other NLS georeferenced layer could also be brought into MapReader too. 

We have a page – [How to find all georeferenced layer URLs](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furl4.mailanyone.net%2Fscanner%3Fm%3D1peg4V-000BGa-54%26d%3D4%257Cmail%252F90%252F1679420400%252F1peg4V-000BGa-54%257Cin4e%257C57e1b682%257C11029744%257C13642207%257C6419ED8FFC201205783AC6220B949AEB%26o%3D%252Fphtu%253A%252Fetse.r0iafl1st.nkcroesptntiooulo.%253Fcokrm%252Fu.o%2525tl%253DAps3hta%2525%25252sFmpF2%2525s.nFuk2l.2dgugs%2525Fieeeeocernrfa%2525ineFlyg2%2525ursFls2-r5t%2526d7%253D0%2525aam%2525C0dCkc174uonth%25250ogcnuru.a.igbCk%25254db07fbb79484bbcbc56a8d2307b1f40%2525C36ef395a7454995418aff58efbf634afCC9%2525%2525%25257070037C8150687858577972oU%25257nknwCnbT%25257ZFpGCWJdsbIeyW38LMjoA4wjiCJAwMILCQDiMVjoIluzi2IJiLITi6CBLak1JwiChW0IXV3Mn%2525C60CD%2525700%252573%2526CC%2525d7Cs7%2525h%253DatQTVIa7ZlJA4GOaZeLzfYwjmohPlEoXBzERon%2525OdfDHM3RXes%2526r%253Drvdee0%26s%3Da6Led4hGvm1o5rzYmfGNEPrtups&data=05%7C01%7Ckmcdonough%40turing.ac.uk%7C4dd0961b34b14952feac08db2aa7ee83%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638150672992211622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fz%2FGehPruvmswsnkBNbmP7AXF8kHbMRCiEHDu%2FNmUSk%3D&reserved=0) – which explains how you can find these using our [Georeferenced Maps Viewer](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furl4.mailanyone.net%2Fscanner%3Fm%3D1peg4V-000BGa-54%26d%3D4%257Cmail%252F90%252F1679420400%252F1peg4V-000BGa-54%257Cin4e%257C57e1b682%257C11029744%257C13642207%257C6419ED8FFC201205783AC6220B949AEB%26o%3D%252Fphtu%253A%252Fetse.r0iafl1st.nkcroesptntiooulo.%253Fcokrm%252Fu.o%2525tl%253DAps3hta%2525%25252sFmpF2%2525s.nFuk2l.x%2525gelFepo2d%2525ortF%2526ae205a%253D%25257C10%2525nm7Cudookcr4ghntui%25250%2525cg.Cuk7a.9bfdb47bb06bc8c4534bfb08ba13d29760f435%2525C4e4a955f74b958e1faaf%25258f6Cf9734CC0%25253%2525767080818857507727U5%2525C797onkTn%2525CnwbbWFdZs3pGoJ8eMIjiyWMLC4AAwDwjoJiLVIjiCQLM2lJIiCuz1IBTaIkhi6VLWwIJXCiC%252506MC3D7n%2525%2525030C7C70%2525t%2526%25257%253DdaaCs0w6BzjLay02kcEoo%2525F0vfyxMaSJRWUgyAahXGIke%2525%2525M9DFo362es%2526r%253Drvdee0%26s%3Dl6Khs2LZPp4TfpqbaukHt3GmUt4&data=05%7C01%7Ckmcdonough%40turing.ac.uk%7C4dd0961b34b14952feac08db2aa7ee83%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638150672992211622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uNkiAYURtj%2FKAlivAGUBsLZzA5AgkH3%2FcLcDMfyCrGw%3D&reserved=0) for any georeferenced layer in there – returning the tileset URL (eg.[https://geo.nls.uk/maps/os/1inch_2nd_ed/{z}/{x}/{y}.png](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furl4.mailanyone.net%2Fscanner%3Fm%3D1peg4V-000BGa-54%26d%3D4%257Cmail%252F90%252F1679420400%252F1peg4V-000BGa-54%257Cin4e%257C57e1b682%257C11029744%257C13642207%257C6419ED8FFC201205783AC6220B949AEB%26o%3D%252Fphtu%253A%252Fetse.r0iafl1st.nkcroesptntiooulo.%253Fcokrm%252Fu.o%2525tl%253DAps3hte%2525%25252.FgoF22.nlmk%2525Fsus%2525ap2Fo%2525s22nF1dh_nic2%2525_e7F%25255d2%25252bzF7d2%2525527%252527x%252555b7Fd%2525y25b2%2525n7%25252%2526.pg5d%2525adaC057t%253Dc701okmd%2525C0gnou%25254tuh.grikacun.0f%252577bb4Cdbc9b54b4b820631dbac8C6f33%252574b0449557e5faf54ffa91984fba938fe600%2525777C%2525C%252508C65508319287%252577587wn7C%2525nonUkGW7CspbZTFW8b3jyJIdejCoiwwLAM4QiMDjCJIALz2oiiuMIVl6BLCkiIIJTCW1hXiLJaw%25256VCDn03IM%25253%25257C007C0s%2525%25257aC%2526dC79dtahxFe%253DKoJ%25252kkRTBRpgAQKcZXQtL2sk7H0i%2525Bs8SxcyWwNce%2526%25253vesrDr0%253Dde%26s%3D0oxAvyCN6G_bEczCvbFfFk7dCiw&data=05%7C01%7Ckmcdonough%40turing.ac.uk%7C4dd0961b34b14952feac08db2aa7ee83%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638150672992211622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BNlgatXZdmw4DLiZsli7q%2Bfao7WD%2BImLaOitTdRooP0%3D&reserved=0)  for any layer).
 
**I don’t know enough about MapReader to know if you need other information other than the tileset URL, but we can do this as necessary. We could also make available the tileset info in other ways, if helpful?**
 
The main aim behind this would be just to make it easier for those using MapReader in future to try it on other NLS georeferenced layers of their choosing.

**Describe the solution you'd like**
Update documentation for Download/Load/Input guidance/worked example to explain options for using NLS tilesets per Chris's notes above. 

- [x] decide where this kind of info should live --> option 3 for input guidance
- [x] are there metadata files for tilesets?

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Need to make sure Chris is OK with re-use of tilesets, any language we might need to include about access, re-use, etc.
- [x ] discussed with Chris

**Comment by kallewesterling** [comment]
They have a nice list here of all the links: https://maps.nls.uk/guides/georeferencing/layers-list.

Perhaps we could refer to this list and what in the TileServer example the URL would go:

----

it is also possible to bring in any other georeferenced layers from the National Library of Scotland into MapReader. Many of these layers have links to WMTS and XYZ URLs, which can be easily found on the NLS website's georeferencing layers list. To do this, you can create a TileServer object and specify the `metadata_path` (the path to your metadata.json file) and the `download_url` (the WMTS or XYZ URL for your tileset).

For example, on [this page](https://maps.nls.uk/guides/georeferencing/layers-list) the NLS lists all their georeferenced tilesets with links. If we wanted to use the "Ordnance Survey - 10 mile, General, 1955 - 1:633,600", we can find its XYZ link on that page: `https://mapseries-tilesets.s3.amazonaws.com/ten_mile/general/{z}/{x}/{y}.png`. Inserted into the script, it would look something like this:

```py
from mapreader import TileServer

my_ts = TileServer(
    metadata_path="path/to/metadata.json",
    download_url="https://mapseries-tilesets.s3.amazonaws.com/ten_mile/general/{z}/{x}/{y}.png",
)
```

**Comment by kmcdono2** [comment]
Thanks for that blurb @kallewesterling! I've used that as a foundation, and added some more comments.
