### ISSUE TITLE
Split contribution guide into different types of contributors

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#146]
Can we split the contribution guide to reflect the different types of contributors:
- Someone who can write a tutorial / worked example
- Someone who can edit/write the docs
- A code developer

Could also add rough idea of skill levels you would need for each. 

**Describe the solution you'd like**
Split the current contribution guide into 2/3 pages to relfect these different groups.

**Comment by kallewesterling** [comment]
Also mentioned in https://github.com/Living-with-machines/MapReader/discussions/147

**Comment by kallewesterling** [comment]
Thanks to @griff-rees - [here’s a really nice "writing documentation" documentation](https://docs.djangoproject.com/en/dev/internals/contributing/writing-documentation/) for inspiration.
