### ISSUE TITLE
Update worked examples and ensure contents are up to date

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#150]
Since we are in the process of changing/updating the code, the current sets of worked examples may end up being outdated. 

**Describe the solution you'd like**
We should go through and update the worked_examples as soon as we are happy no further 'big' changes to the code are coming up.

**Describe alternatives you've considered**
Could do it each time we make a change but feels like it might be easier to do in one go?

**Comment by kmcdono2** [comment]
Can we update the repo so that:

- the `datasets/small_mnist` is inside `non-geospatial` or `persistent_data` (whatever is more appropriate)
- remove/archive/?? `classification_one_inch_maps` (I think we are ready for this, as new workshop notebook supercedes/improves?)

**Comment by rwood-97** [comment]
Agree with these.
Should I also move ``persistant_data`` to the ``geospatial`` (and rename to something more intuitive?)

**Comment by rwood-97** [comment]
Closed by PR #199
