### ISSUE TITLE
[meta] planning MapReader launch

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#153]
Meta ticket for various planning bits related to MapReader Launch on June 7-8.

Detailed plans here: https://docs.google.com/document/d/1mGCjNSgaFw2wfYzL2kc6sDvLessKe_BEKTNcDiRPH0A/edit

**Comment by rwood-97** [comment]
Once PRs are merged: 

- [ ] Update version 
- [ ] Publish to PyPI
- [ ] Publish to conda forge (note this: #162 )

**Comment by kmcdono2** [comment]
@rwood-97 have just finished making comments in the ReviewNB version of notebook for the workshop
