### ISSUE TITLE
Separate "Basic" and "Advanced" documentation for the load module.

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#159]
This could be done in a couple of ways:

- Using subheading within the Load and Patchify page
- Have two separate pages for Basic and Advanced

In either case, highlight to the user when that the Advanced is not required for an initial walk-through MapReader.

**Comment by rwood-97** [comment]
https://github.com/Living-with-machines/MapReader/pull/140#discussion_r1170260641 
When loading files using ``loader``, ``loadPatches`` or ``mapImages.loadParents``:

> I think that it might be legitimate to mention globs here, with suitable wording to not scare those who don't know about them. something a long the lines of:
> 
> .. note:: For those familiar with the concept, when used in this way, the loader function mays use of globs <https://docs.python.org/3/library/glob.html>_ to locate the files.
> 
> Also, I think it is appropriate to mention that the input can only be strings and not pathlib.Path objects.
