### ISSUE TITLE
find or re-create railspace/building model from SIGSPATIAL paper

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#187]
**Is your feature request related to a problem? Please describe.**
We don't have the model, need to have it saved and documented.

https://dl.acm.org/doi/10.1145/3557919.3565812

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rwood-97** [comment]
1. Download patches from zenodo
2. Find annotations from before - @kmcdono2 do you know where to look for these? are these the same as the annotations on zenodo which are split into train/val/test?
3. Fine-tune a pretrained _resnest101e_ using annotations as training data - will need to ensure set up is the same as before. WIll email Kasra to find out if there are any scripts about.

**Comment by kmcdono2** [comment]
> 2\. re these the same as the annotations on zenodo which are split into train/val/test?

Yes, the zenodo set contains everything. You've got it right - it's the combo of the train/val/test that are the total annotations.

**Comment by rwood-97** [comment]
**Adding here so we don't loose anything:**

Currently models are located on `visionwithmachines-GPU` azure VM in `/datadrive/kasra/MapReader_BACKUP_BEFORE_PUBLIC/examples/mapreader_paper/` directory.

Final model used is found at `/datadrive/kasra/MapReader_BACKUP_BEFORE_PUBLIC/examples/mapreader_paper/step02_train_models/models_resnest50d_4s2x40d_timm_pretrain`. It is checkpoint_8. 

Currently, entire models are saved as .pkl files and so need same package versions if you want to use. These are:
- timm==0.5.4
- pip install torch==1.10.2
- torchvision==0.11.3

Torch has [option also to save model state_dict](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html) for easier transfer of models between machines. These files can be generated for each model. 

**To do:**

- [ ] Create model state_dict files for each model
- [ ] Export all model files as .tar and upload somewhere (?)
- [ ] Ensure saving of state_dict is added to new mapreader
- [ ] Recreate exp. with new mapreader and old model - check we get same outputs.

**Comment by rwood-97** [comment]
https://huggingface.co/models?search=rwood-97 models are here for now

**Comment by rwood-97** [comment]
- [ ] Transfer models to LWM org (tag with mapreader)
- [ ] Make ticket to add model cards to HF models
