### ISSUE TITLE
Make patch data to publicly accessible site for visualisation during workshop.

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#191]
- [ ] Add patches (not just centre points) to one or all of these resources:

https://zenodo.org/record/7147906#.ZG3YD-zMI-Q
https://huggingface.co/Livingwithmachines
https://huggingface.co/datasets/Livingwithmachines/MapReader_Data_SIGSPATIAL_2022/blob/main/MapReader_Data_SIGSPATIAL_2022.py

- [ ] Create a reproducible method (eg a notebook or simular) to convert from there into a format/hosting suitable for serving into Felt or other visualisation tool.

- [ ] Update Zenodo record with info about centroid-to-patch code and the new data. (check who has edit-permissions on Zenodo record).

**Comment by kmcdono2** [comment]
FYI viz prep tickets in viz repo:

https://github.com/Living-with-machines/mapreader_viz/issues/18

https://github.com/Living-with-machines/mapreader_viz/issues/17

https://github.com/Living-with-machines/mapreader_viz/issues/16

**Comment by kmcdono2** [comment]
We've decided to re-run the experiments and will address this and publish new datasets when complete. No need to add to existing datasets now.
