### ISSUE TITLE
Testing `MapReader`

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#2]
Hi All 👋🏼

I will be testing `MapReader` install and the demo notebooks run to evecute the analysis. I will document my process here

- [x] Installation
  - [x] Install `git clone git@github.com:Living-with-machines/MapReader.git` 
  - [x] ` git branch` -> <span style="color:green">`* dev`</span>
  - [X] `git pull origin dev`
  - [X] `poetry install`
  - [X] `poetry shell`
    - this command was not included in the `README.md` (unlike `conda activate ...`)
- [x] Notebooks code execution 
  - [x] `001_retrieve_patchify_plot.ipynb`
  - [x] `002_annotation.ipynb`
  - [x]  `003_train_classifier.ipynb`
  - [x]  `004_inference.ipynb`

**Comment by ChristinaLast** [comment]
I didnt forget about this - but dont have this file:/ closest it has generated is:
```
find . -type f -iname "patch-4500-950-4550-1000*"
./patch-4500-950-4550-1000-#map_101168609.png#.PNG
./patch-4500-950-4550-1000-#map_101167745.png#.PNG
./patch-4500-950-4550-1000-#map_101168702.png#.PNG
./patch-4500-950-4550-1000-#map_101168036.png#.PNG
```

**Comment by kasra-hosseini** [comment]
OK, I see. In our tutorials, we use the following lines to find and retrieve maps:

```
tileserver.query_point([51.53, -0.12])
# # if append = False, only the last query will be stored
tileserver.query_point([51.4, 0.08], append=True)
tileserver.query_point([51.4, -0.13], append=True)
tileserver.query_point([51.52, 0.03], append=True)
```

I assume you used different query points? Could you check this, please?

If you use the above commands, the following maps will be stored locally:

```
maps_tutorial
├── map_101168609.png
├── map_101168618.png
├── map_101168702.png
├── map_101168708.png
└── metadata.csv
```

and after patchifying, you will have `patch-4500-950-4550-1000-#map_101168618.png#.PNG` (I hope :) ).

(Note that  `#map_101168618.png#` in the file name refers to the parent/original map.)

**Comment by kasra-hosseini** [comment]
I hope this solves the issue; however, I think we need a function in the `loadAnnotations` class to check the consistency between the read annotations and available patches (to avoid future issues like this). I will open a ticket for this.

**Comment by ChristinaLast** [comment]
Yes, I have changed these to:
```
tileserver.query_point([51.53, -0.12])
# # if append = False, only the last query will be stored
tileserver.query_point([52.4033848, -1.534723], append=True)
tileserver.query_point([51.5956638, -0.0650902], append=True)
tileserver.query_point([51.4833289, -0.1081195], append=True)
tileserver.query_point([52.9449011, -1.2420748], append=True)
```
when printing these queries using:
`tileserver.print_found_queries()`

I get:
```
------------
Found items:
------------
URL:     	https://maps.nls.uk/view/101168609
filepath:	map_101168609.png
coords:  	[-4.06538210e-01  2.07213000e-02  5.15026204e+01  5.16848974e+01]
index:   	378
====================
URL:     	https://maps.nls.uk/view/101168036
filepath:	map_101168036.png
coords:  	[-1.6382443  -1.20698142 52.39222153 52.57026517]
index:   	294
====================
URL:     	https://maps.nls.uk/view/101168702
filepath:	map_101168702.png
coords:  	[-4.15144570e-01  1.04388000e-02  5.13292371e+01  5.15114618e+01]
index:   	390
====================
URL:     	https://maps.nls.uk/view/101167745
filepath:	map_101167745.png
coords:  	[-1.62575507 -1.18923268 52.91266376 53.09077452]
index:   	250
====================
```

**Comment by ChristinaLast** [comment]
Rerunning the notebooks results in a similar error:
`FileNotFoundError: No such file: '/Users/clast/Documents/2021_projects/LwM/MapReader/examples/classification_one_inch_maps_001/maps_tutorial/slice_50_50/patch-3750-2250-3800-2300-#map_101168618.png#.PNG` 

A different `patch` label, but the same non-existent `map` label, (`map_101168618`).

**Comment by kasra-hosseini** [comment]
In `003_train_classifier.ipynb`, are you running:

```python
annotated_images.load("./annotations_one_inch/rail_space_#kasra#.csv", 
                      path2dir="./maps_tutorial/slice_50_50")
```

`rail_space_#kasra#.csv` is a file that I created for the tutorials in which we have annotated that patch (i.e., `patch-3750-2250-3800-2300-#map_101168618.png#.PNG`), see: https://github.com/Living-with-machines/MapReader/blob/main/examples/classification_one_inch_maps_001/annotations_one_inch/rail_space_%23kasra%23.csv#L180

It seems to me that there is an inconsistency between the annotation file, i.e., `./annotations_one_inch/rail_space_#kasra#.csv` and your queried maps. You can either use your own annotation files (the ones that you create here: https://github.com/Living-with-machines/MapReader/issues/9) or query/patchify these maps (following the tutorial) as `rail_space_#kasra#.csv` contains annotations for these maps

```
tileserver.query_point([51.53, -0.12])
# # if append = False, only the last query will be stored
tileserver.query_point([51.4, 0.08], append=True)
tileserver.query_point([51.4, -0.13], append=True)
tileserver.query_point([51.52, 0.03], append=True)
```

Can you also take a look at this issue: https://github.com/Living-with-machines/MapReader/issues/7. I think this is a very important one that needs to be addressed soon. (I will work on it this week).

**Comment by ChristinaLast** [comment]
ok, when using my own annotations it works, I think I am understanding a little more about how the package works! 
Should I add a little 🚨🚨 WARNING: 🚨🚨 that if a user changes the locations for the map retrieval, they will need to  develop and use their own annotation `csv`? 

Im not sure if one of your patches already acheives this though! 🙈

I am taking a look at #7 now!

**Comment by kasra-hosseini** [comment]
@ChristinaLast Thanks. It would be great if you add 🚨🚨 . I will also add new functionality this week to check the consistency (i.e., overlap) between the annotation list and sliced images.

**Comment by kasra-hosseini** [comment]
@ChristinaLast Thank you again for the tests. I close this issue now.
