### ISSUE TITLE
Deploying `MapReader` through `binder`

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#21]
- [x] @ChristinaLast and @andrewphilipsmith to walk through `binder` deployment
  - [x] adding `requirements.txt` with no hashed libraries for binderhub deployment

**Comment by ChristinaLast** [comment]
Deployed on binderhub here: https://hub.gke2.mybinder.org/user/living-with-machines-mapreader-ynvxqog1/lab

**Comment by kasra-hosseini** [comment]
@ChristinaLast This is great, thanks. Let me know when the PR is ready, and I am happy to test the notebook on Binder.
