### ISSUE TITLE
add version # for MapReader used in SIGSPATIAL paper (arxiv version)

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#213]

**Comment by rwood-97** [comment]
- mapreader == 0.3.3

other packages for if you want to use models ([see here](https://github.com/Living-with-machines/MapReader/issues/187#issuecomment-1600963456)):
- timm==0.5.4
- pip install torch==1.10.2
- torchvision==0.11.3

**Comment by rwood-97** [comment]
@kasra-hosseini Would it be possible to add these into the archive paper somewhere? Maybe in a footnote

**Comment by kmcdono2** [comment]
emailed kasra

**Comment by kmcdono2** [comment]
Let's just close this...
