### ISSUE TITLE
Restructuring `MapReader` `README.md`

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#22]
- [x] @kmcdono2 to add comments on updated demo material and structure and `README.md`

**Comment by ChristinaLast** [comment]
@kmcdono2 do you have any update on this?

**Comment by kmcdono2** [comment]
My comments - will translate these into actual text for the readme shortly. [mapreader_readme.pdf](https://github.com/Living-with-machines/MapReader/files/7995918/mapreader_readme.pdf)

**Comment by kasra-hosseini** [comment]
@kmcdono2 Thanks for your comments. Based on your suggestions/comments, it seems to me that you want to preset MapReader as primarily a library to work with (historical) maps which can also be used in other fields. This is, of course, how we actually developed MapReader. However, I think we can reformat the README file a bit differently: 

We present MapReader as a library that can work with images and maps, and that, we have specialized tools/functionalities to work with different types of data (e.g., maps). Then, in the README, we have sections for each use case, e.g., how MapReader can be used for historical maps, or how historians can use MapReader. Also, how we can use MapReader for plant images (and later for remote sensing). Although this is not how we developed MapReader, this is how it is going to be further developed, e.g., my contributions to the library will revolve around plant images and remote sensing for the next few weeks/months (+ of course, historical maps).

In terms of restructuring the README, I would suggest:

- Gallery of use cases (maps and plant images for now)
- What is MapReader? (broadly speaking, e.g., fig 1 in our paper)
- Installation and setup
- Use cases
    - Maps
        - MapReader's tools/functionalities to work with maps
        - Demo: Historical maps
            - Move the railspace/building figure to this section
            - How MapReader can help historians
            - notebooks to work with OS maps
    - Scientific (non-map) images
        - Demo: plant phenotyping

And so on...

We can also add a section: "Why is it called MapReader?" (maybe as a subsection in "What is MapReader? ") and briefly, in 2-3 lines, say that we originally developed MapReader for maps, but now, we are using it and further exploring its application to other fields/datasets.

How does it sound?

**Comment by kmcdono2** [comment]
Moving some of @jl106jml comments from PDF to here:

- "I can see it may be necessary to elide maps and other images at this stage but ideally we need a dedicated release and ReadMe for Map cv work and a second for the broader CV method which can be applied to multiple image types - and which logically would NOT be called MapReader but perhaps something more general denoting its method of Cv - say PatchReader or Patch Weaver or similar. Combining the two is likely to cause confusion - it will look too applied/'mappy' for cv specialists and too general for those wanting to work with historic maps at scale.?
- Re: install instructions via Anaconda "Anaconda says you may wish to install only Miniconda (conda, its dependencies & Python) - is that all one needs, if so this should say so (if NOT probably that needs saying too). NB I cant install Anaconda as I am running Windows 7 and it requires 8 or higher... worth saying here? This means I can't actually test any of these things sadly." --> I think this just requires more explanation about anaconda/miniconda
- Re code snippits: "A non-prgramming user wont know that these boxes are instructions - they also wont necessarily know how to give commands to conda. Best to spell these out." --> We can point users to intros to command line before they use this tool.

**Comment by DavidBeavan** [comment]
Hiya all, my strong suggestion is to stick to the original formulation, prior to @kasra-hosseini  ’s comments. I see @kasra-hosseini ’s point, it may well be neater that way, but it’s not how it happened, that would rewrite the development history. I fear that’s a dangerous route to go down, especially as we’re wanting to be careful about provenance.

This is the way I see it: MapReader is historic maps and came first (the chain of citations from future work should cascade back to MapReader); it has since been generalised, as it could give novel solutions to challenges in other disciplines; that technique and code is called xxxx; xxxx has been used to investigates plant phenotyping...

Can you collectively get behind that?

**Comment by kmcdono2** [comment]
Thanks @DavidBeavan this is super helpful. I've been thinking a lot about this and had a really useful chat with Malvika today as well about how you build a foundation for a project like this that can have multiple goals. Here is a proposal for how to organize the README that should account for both its origin story and important historical source motivation & its future as reusable, extendable code.

The README is basically a landing page that has 3 paragraphs and links out to 3 pages:
1. Origin story and motivation to use computer vision in a way that is driven by careful attention to the provenance/history of input images. This was first maps on LwM. [tell this story a bit] Next it will/could be XXX.
2. Generalizable research/our approach to code & data sharing - e.g. how to contribute/get involved/ask questions.
3. Outreach/training - e.g. how to use this depending on who you are.

@kasra-hosseini @dcsw2 and others, what do you think? Does this give space for different kinds of information to be showcased?

**Comment by kasra-hosseini** [comment]
Sorry for the delay. Sure, sounds good.

**Comment by dcsw2** [comment]
Yes, this sounds like a very sensible approach.

D.


On 7 Feb 2022, at 16:45, Katie McDonough ***@***.******@***.***>> wrote:



Thanks @DavidBeavan<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDavidBeavan&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3XccWpgoDait551jAhi0c6t%2FjrHjs5BBoxFgFNEV0bE%3D&reserved=0> this is super helpful. I've been thinking a lot about this and had a really useful chat with Malvika today as well about how you build a foundation for a project like this that can have multiple goals. Here is a proposal for how to organize the README that should account for both its origin story and important historical source motivation & its future as reusable, extendable code.

The README is basically a landing page that has 3 paragraphs and links out to 3 pages:

  1.  Origin story and motivation to use computer vision in a way that is driven by careful attention to the provenance/history of input images. This was first maps on LwM. [tell this story a bit] Next it will/could be XXX.
  2.  Generalizable research/our approach to code & data sharing - e.g. how to contribute/get involved/ask questions.
  3.  Outreach/training - e.g. how to use this depending on who you are.

@kasra-hosseini<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkasra-hosseini&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qshuyzDWEtpVLiCZ9%2B9THYxoXdZXsLM2bVYTGwxlna4%3D&reserved=0> @dcsw2<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdcsw2&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GlgqtXKYruJh7fuMh8fCC4OV4zfQhdvnskbutIl%2BlR0%3D&reserved=0> and others, what do you think? Does this give space for different kinds of information to be showcased?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLiving-with-machines%2FMapReader%2Fissues%2F22%23issuecomment-1031680262&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xbS2yZyl8xBxF0VpEe%2BXkN%2B26A72GwwOB5UbD6BIBcc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIF2PDVDCNAIDDBDV7CNKV3UZ7ZJJANCNFSM5NF5PAFQ&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1nzeEjuKXQQO%2FVa8yepTMrt%2BQDNh1GquNgq4RUgYiR4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7RwqDy175gKAwQism3tFz5LExqD8SS3QXfmoHUMxAVs%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdwilson%40turing.ac.uk%7C1cf5f4cfcd4c4459db4d08d9ea5933ee%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C637798491107332776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2TVPeziKSAcCZjxGHtE176Gw4tj%2FPyxBj3AcmnhlOmk%3D&reserved=0>.

**Comment by kmcdono2** [comment]
Hi all, fantastic. I am [drafting the new text here before doing a pull request in the repo.](https://hackmd.io/bcffLmxHSnCQH8xQE4Eneg)

Will get to some things today, and will pick it up when I return on March 3. Please feel free to leave comments/requests/etc. there or here.

**Comment by kasra-hosseini** [comment]
Thanks @kmcdono2 for this. I am making some changes to the HackMD file.

**Comment by kmcdono2** [comment]
@kasra-hosseini @dcsw2 - I've incorporated @DavidBeavan's suggestions and I think this is ready to go pending your final comments.
https://hackmd.io/bcffLmxHSnCQH8xQE4Eneg

A few notes:
- I fully imagine moving a good deal of this content to something like a jupyter book. But it's living here temporarily.
- Kasra there are a few places with notes about content for you to add/check.

When ready, would you like me to submit it as a pull request or just edit the README?

**Comment by kmcdono2** [comment]
[One further draft](https://hackmd.io/Js6ckPjKS8SYCA9RgE6o_w), attempting to be slightly more generic:
- moves some of the map-specific content to the new "Getting started with maps" draft text for the Binder notebook
- proposes other sections that could be moved to a jupyter book

**Comment by kasra-hosseini** [comment]
See: https://github.com/Living-with-machines/MapReader/pull/38 for discussion/changes.
