### ISSUE TITLE
add page to docs about outputs (papers, events)

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#231]
Need central place to document all outputs related to MapReader.

- [x] create new page in docs site
- [x] decide name for this new page
- [x] sections so far: 1) events, 2) papers, 3) talks, 4) data, 5)models?
- [x] where save slides?

**Comment by rwood-97** [comment]
Always save slides in mapreader.team gmail accounts drive

**Comment by rwood-97** [comment]
@kmcdono2  to add content, branch is rw_docs
