### ISSUE TITLE
check all outputs in BL repo

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#237]
- [x] Check this list https://docs.google.com/spreadsheets/d/1aVLSc8TOiT77A1Q0Wbw5W50i8xuVR8go8MGITaGZhiw/edit#gid=178226612
- [x] anything missing from that list
- [x] add to BL repo

**Comment by kmcdono2** [comment]
Instructions from @mialondon :
A quick note to share a new form that you can use to describe outputs for deposit in the Research Repository: [https://forms.office.com/Pages/ResponsePage.aspx?id=t0ykIcP5AE-a-r0ejoi82QBILaDIPdFMqSHJBM7LVQxUMjk4VjJJRUtMR0tYMzJWQVBaVFRZTFpPRy4u](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforms.office.com%2FPages%2FResponsePage.aspx%3Fid%3Dt0ykIcP5AE-a-r0ejoi82QBILaDIPdFMqSHJBM7LVQxUMjk4VjJJRUtMR0tYMzJWQVBaVFRZTFpPRy4u&data=05%7C01%7Ckmcdonough%40turing.ac.uk%7C38c327f26db94288ecfa08db60fef12c%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638210420311617598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CN8gFqrL3djs0agHqveCkLoxRWeUDL0QRjsoTGpbweg%3D&reserved=0)
 
The BL team are turning deposit requests around quite quickly at the moment, so it’s ideal if you’ve got upcoming publications and want to link to datasets and code, or just want the satisfaction of getting a lot of items off your To Do list! (As a reminder, all project outputs should be sent to the repository, even if they’re also uploaded elsewhere. It can handle items that can’t be made public before a certain date, etc, so embargoes are fine).
 
Mariona’s already tested it and asked about the ‘Organisational unit’ field – select “Digital Scholarship” in that section.
 
Enter “Living with Machines” in the project name field.
 
This will ensure that project outputs are grouped together. I’ve included a screenshot from Graham so you can see how the funder, project, etc information comes together.

**Comment by kmcdono2** [comment]
MapReader outputs:

- [ ] code/software library on Github
- [ ] JVC paper
- [ ] ACM SIGSPATIAL paper
- [ ] arxiv paper
- [ ] railspace and building datasets (+ README/data card) published first on Zenodo
- [ ] model for railspace and building datasets (+ model card)
- [ ] documentation site (w/jupyter notebooks)

**Comment by kmcdono2** [comment]
Other related:

- [x ] Programming historian lessons

**Comment by kmcdono2** [comment]
Waiting for ACM open access fee to be paid so I can load paper to BL repository.

**Comment by rwood-97** [comment]
@kmcdono2 to email Andre when sigspatial paper is sorted.

**Comment by kmcdono2** [comment]
DONE!
