### ISSUE TITLE
Add model cards to hugging face models

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#240]
All models from 2021 paper are now on HF.
We need to make model cards for each.

**Comment by kmcdono2** [comment]
- model description @rwood-97  (ask @kasra-hosseini to review)
- model sources @rwood-97 
- uses @kmcdono2 
- bias @kmcdono2 
- how to get started with model @rwood-97 (point to documentation for classify)
- training details @kmcdono2 (ask @kasra-hosseini  to review)
- evaluation @kmcdono2

**Comment by kmcdono2** [comment]
- [ ] https://huggingface.co/Livingwithmachines/mr_resnest101e_timm_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_swsl_resnext101_32x8d_timm_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_vit_base_patch16_224_timm_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_tf_efficientnet_b3_ns_timm_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_resnest101e_timm_no_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_swin_base_patch4_window7_224_timm_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_resnet152_torch_pretrain
- [ ] https://huggingface.co/Livingwithmachines/mr_resnest50d_4s2x40d_timm_pretrain (@kmcdono2 working on this one first)
