### ISSUE TITLE
Go through Azure resources and mark as keep/delete

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#242]
We need to mark which MapReader-related Azure resources to keep/delete.

> How to note which Azure resources need to stay:
> - Clear out any unused resources (it’s better to remove them now if they are not needed)
> - Label things at the lowest level possible, e.g. VMs and Disks, NOT whole resource groups
> - Use the ‘tags’ Azure feature to add
> - Tag Name: lwm_person; Tag value: <email address of LwM responsible person>
> - Tag Name: lwm_keep; Tag value: Y
> - Everything else is assumed to be disposable
> - LwM reserves the right to deallocate (turn off) VMs and downgrade storage access levels
> - This is an initial draft of guidance, help improve it

This should be done by the end of July.

**Comment by rwood-97** [comment]
Here are potentially ones to deal with (I searched for visionwithmachines and maps):

NAME | TYPE | RESOURCE GROUP
-- | -- | --
3w4petvt6gsfkjupyter | Storage account | visionwithmachines-jupyterhub
jupyter-PublicIP | Public IP address | visionwithmachines-jupyterhub
jupyter-vm-nsg | Network security group | visionwithmachines-jupyterhub
jupyter-VMNic | Network Interface | visionwithmachines-jupyterhub
jupyter-VNET | Virtual network | visionwithmachines-jupyterhub
maps_large | Disk | visionwithmachines
maps_large_03 | Disk | visionwithmachines
TLJH-Ubuntu | Virtual machine | visionwithmachines-jupyterhub
TLJH-Ubuntu_OsDisk_1_80c660d9ecf04626af5f40312353b74e | Disk | visionwithmachines-jupyterhub
visionwithmachines | SSH key | visionwithmachines
visionwithmachines-g582 | Network Interface | visionwithmachines
visionwithmachines-GPU | Virtual machine | visionwithmachines
visionwithmachines-GPU-ip | Public IP address | visionwithmachines
visionwithmachines-GPU-nsg | Network security group | visionwithmachines
visionwithmachines-GPU_DataDisk_2 | Disk | visionwithmachines
visionwithmachines-GPU_lun_0_2_7008703373b947ce99d590cac8158b98 | Disk | visionwithmachines
visionwithmachines-GPU_OsDisk_1_d6d0d8519b4a40c9b7fb7d7dcf459224 | Disk | visionwithmachines
visionwithmachines-vnet | Virtual network | visionwithmachines
visionwithmachinesdiag | Storage account | visionwithmachines
vwm-maps-annotation | Disk | visionwithmachines-jupyterhub
jupyter-maps | Virtual machine | jupyter-maps
jupyter-maps-ip | Public IP address | jupyter-maps
jupyter-maps-nsg | Network security group | jupyter-maps
jupyter-maps-vnet | Virtual network | jupyter-maps
jupyter-maps248 | Network Interface | jupyter-maps
jupyter-maps_OsDisk_1_e562a9a7980e45339df161fb470a76e0 | Disk | jupyter-maps
jupyterhub-mapshack-995 | Network Interface | livingwithmachines
jupyterhub-mapshack-gpu-ip | Public IP address | livingwithmachines
jupyterhub-mapshack-gpu-nsg | Network security group | livingwithmachines
jupyterhub-mapshack-gpu_lun_0_2_d25ef891db774b678cdd1d896c416a87 | Disk | livingwithmachines
jupyterhub-mapshack-gpu_OsDisk_1_fb942f1a4cfe406b810d280da3260fb1 | Disk | livingwithmachines
jupyterhubmaps | Virtual machine | livingwithmachines
jupyterhubmaps-ip | Public IP address | livingwithmachines
jupyterhubmaps-nsg | Network security group | livingwithmachines
jupyterhubmaps359 | Network Interface | livingwithmachines
jupyterhubmaps37 | Network Interface | livingwithmachines
jupyterhubmaps_DataDisk_0 | Disk | livingwithmachines
jupyterhubmaps_OsDisk_1_fa1c79e32bfd4ab7a1762dd0a59adb8b | Disk | livingwithmachines
jupyterhubmaps_OsDisk_1_fa5a71159fdf47588d5b69cf398d4136 | Disk | livingwithmachines
jupyterhubmapsip971 | Public IP address | livingwithmachines
jupyterhubmapsnsg755 | Network security group | livingwithmachines
jupytermapsdiag | Storage account | jupyter-maps
map-database | Virtual machine | edinburgh
map-database-ip | Public IP address | edinburgh
map-database-nsg | Network security group | edinburgh
map-database739 | Network Interface | edinburgh
map-database_disk1_9e3be1b7ddb24c14a4138789a050d4d3 | Disk | edinburgh
mapreader-viz | Virtual machine | mapreader-viz_group
mapreader-viz-ip | Public IP address | mapreader-viz_group
mapreader-viz-nsg | Network security group | mapreader-viz_group
mapreader-viz-vnet | Virtual network | mapreader-viz_group
mapreader-viz491_z1 | Network Interface | mapreader-viz_group
mapreader-viz_OsDisk_1_5817e16d8f2e4575954809c4ba108b5a | Disk | mapreader-viz_group
maps-inference | Virtual machine | maps-inference
maps-inference-ip | Public IP address | maps-inference
maps-inference-nsg | Network security group | maps-inference
maps-inference-vnet | Virtual network | maps-inference
maps-inference163 | Network Interface | maps-inference
maps-inference_DataDisk_1 | Disk | maps-inference
maps-inference_lun_0_2_a35ac5f910bf421bb53d9fc6f36546db | Disk | maps-inference
maps-inference_OsDisk_1_94ba0798adfa4011861565d81676fbcb | Disk | maps-inference
maps_large | Disk | visionwithmachines
maps_large_03 | Disk | visionwithmachines
mapshackday | Virtual machine | mapshackday
mapshackday-ip | Public IP address | mapshackday
mapshackday-nsg | Network security group | mapshackday
mapshackday-vnet | Virtual network | mapshackday
mapshackday655 | Network Interface | mapshackday
mapshackday_OsDisk_1_8982214c47f2415e9f2c5ef288d3c9fc | Disk | mapshackday
mapshackdaydiag | Storage account | mapshackday
mapsinferencediag | Storage account | maps-inference
mapsworkshop | Storage account | defaultresourcegroup-suk
vwm-maps-annotation | Disk | visionwithmachines-jupyterhub

**Comment by kmcdono2** [comment]
Let's go through these 1 by 1 next week when you're back @rwood-97. 

A few points:
- we don't necessarily need to keep VMs alive, but we should document their details so we can re-create as needed in new
- I need to know this same info to get a compute estimate for new projects (asap)
- Storage-wise: we want to keep running, and either download or or transfer to new grant storage for BL OS maps + NLS maps early samples

**Comment by kmcdono2** [comment]
Made updates in spreadsheet.
