### ISSUE TITLE
link Github repo to zenodo to mint DOIs for releases

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#252]
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by kmcdono2** [comment]
@rwood-97 I made a `[draft release](https://github.com/Living-with-machines/MapReader/releases/edit/untagged-2fd3aec1990a8efeb216)` + enabled zenodo for this repo, but I'm not sure it's a good idea to create a new release ONLY so that we can get zenodo to automatically mint the DOI. What do you think, should I publish the release?

<img width="892" alt="Screenshot 2023-07-26 at 14 35 42" src="https://github.com/Living-with-machines/MapReader/assets/20363927/1d27efde-b9a8-40de-84bf-d5e29a348ad4">

**Comment by rwood-97** [comment]
plan is to make new release as 'End of LwM' and then link with DOI
