### ISSUE TITLE
update model cards with more detail in hugging face

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#254]
**Is your documentation update related to a problem? Please describe.**
Return to model cards to include new fields as we have more detail to add.

All mapreader models on Hugging Face using `mapreader` tag: https://huggingface.co/models?other=mapreader

**Describe the solution you'd like**
Decide what parts of template to use as we add more detail in future experiments.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by rwood-97** [comment]
I think we did this so am closing
