### ISSUE TITLE
add contributors table to README

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#255]
like: https://github.com/alan-turing-institute/the-turing-way#contributors

**Comment by rwood-97** [comment]
- [x] Install 
- [ ] [Add everyone](https://allcontributors.org/docs/en/bot/usage)

**Comment by rwood-97** [comment]
@all-contributors
please add @kmcdono2 for research ideas
please add @dcsw2  for research

**Comment by rwood-97** [comment]
@all-contributors
please add @kasra-hosseini for code

**Comment by rwood-97** [comment]
@all-contributors please add @kallewesterling for code, doc

**Comment by rwood-97** [comment]
@kmcdono2 can we discuss at some point who to add for what (I've added some but mostly was just playing with how it works (it breaks if you do two at a time I think?))

**Comment by kmcdono2** [comment]
Yes - I'll re-read the turing way example and we could discuss. Will slack about a time.

**Comment by rwood-97** [comment]
@all-contributors @ChrisFleet for data

**Comment by rwood-97** [comment]
https://github.com/all-contributors please add @ChrisFleet for data

**Comment by rwood-97** [comment]
@all-contributors please add @ChrisFleet for data

**Comment by rwood-97** [comment]
@all-contributors please add @kasparvonbeelen for ideas, review, research

**Comment by rwood-97** [comment]
@all-contributors please add @dcsw2 for ideas, talk, docs and eventOrganizing

**Comment by rwood-97** [comment]
@all-contributors please add @rwood-97 for ideas, talk, tutorials, review, maintenance, research

**Comment by rwood-97** [comment]
@all-contributors please add @kallewesterling for maintenance, review, talk,

**Comment by rwood-97** [comment]
@all-contributors please add @andrewphilipsmith for code, docs, mentoring, review,
