### ISSUE TITLE
prepare JOSS submission

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#257]
https://joss.readthedocs.io/en/latest/submitting.html#

https://joss.theoj.org/papers/new 

Draft md file: https://hackmd.io/ELc-ybBpTMeKQ34CPhYTPA?edit

**Comment by kmcdono2** [comment]
- [ ] need title that is different from SIGSPATIAL paper

**Comment by kmcdono2** [comment]
@rwood-97 can you check that the JOSS paper file compiles per these instructions? 
https://joss.readthedocs.io/en/latest/submitting.html#checking-that-your-paper-compiles

File - 
https://hackmd.io/ELc-ybBpTMeKQ34CPhYTPA?edit 

I'll put an updated bib file in slack.

**Comment by rwood-97** [comment]
I think it seems okay, will send pdf on slack
