### ISSUE TITLE
update contributors page

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#268]
@davanstrien @ov212 @ruthahnert @jl106jml - we would like to credit your work (past, present, maybe future!) on MapReader on the https://github.com/Living-with-machines/MapReader/blob/main/Contributors.md page.

@jl106jml - I have used you as an example and added an entry for you already (I debated current vs past, and can change this depending on your wishes!)

If you would agree to be listed, would you either let me know that you are OK with this, or make the change your self following the formatting/data types in the table?

**Comment by ruthahnert** [comment]
This is very nice and I’d be delighted to be credited in a manner similar to Jon. Thank you.

**Comment by ov212** [comment]
Thank you @kmcdono2 - yes happy with this

**Comment by kmcdono2** [comment]
Thanks all! Making updates now.
