### ISSUE TITLE
plan MapReader community calls

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#284]
Aim: have monthly community calls for MapReader 

Decisions to make:
- also include MRM? or alternate weeks?
- structure?
- ultimate goals? (e.g. organize MapReader feature development? showcase applications? etc.)

Action items:
- [x] make list of places to send announcement
- [x] make google doc for agenda template (use IIIF call docs as example)
- [ ] schedule some demos 
- [ ] how to organize people who want to contribute?

**Comment by kmcdono2** [comment]
- [ ] @rwood-97 check in w/Peak District NP about 10 minute demo about work in progress
- [ ] @kmcdono2 make google doc template - includes way to access zoom link 
- [ ] propose April 18 4pm as next one (bi-monthly)
- [ ] katie blurb


Where to advertise:
- [ ] DHSI listserv @kmcdono2 
- [ ] DH French listserv @ruthahnert 
- [ ] CHR discourse @dcsw2 
- [ ] scivision channel @rwood-97 
- [ ] mapreader workspace @kmcdono2 
- [ ] ask Dave for RSE comms @rwood-97 
- [ ] lancaster DH list @kmcdono2 
- [ ] N8 comms - ask Luca @kmcdono2 
- [ ] ask Ruth to share at QM @dcsw2 
- [ ] send to Chris @kmcdono2 
- [ ] send to Xavier and Glenn, Carmen @kmcdono2 
- [ ] bluesky @kmcdono2 
- [ ] mastodon @dcsw2

**Comment by kmcdono2** [comment]
Community Call Template: https://docs.google.com/document/d/1iMoEBNvNMKCvXAN3YfCFP-96HIenFKj1vb8mKfqTQqU/edit#heading=h.t71vmryvuznf

**Comment by kmcdono2** [comment]
@rwood-97 - are the peak district people ok to present? if so, can you add their names and the name of their project to the agenda on the Feb doc?

**Comment by kmcdono2** [comment]
@rwood-97 - can we add a page to the docs titled "Community Calls" where there is a list of dates and the info on how to get the meeting invite?

**Comment by rwood-97** [comment]
>Did we decide it was OK to put it in the doc?

I think the "join the workspace for a link" approach seems good. 

Maybe for the email give the mapreader.team@gmail.com email - I can set up forwarding to my Turing email (shall I also do yours + @dcsw2 's turing emails?)

>are the peak district people ok to present? if so, can you add their names and the name of their project to the agenda on the Feb doc?

Just double checking, I think yes.

**Comment by kmcdono2** [comment]
> Maybe for the email give the [mapreader.team@gmail.com](mailto:mapreader.team@gmail.com) email - I can set up forwarding to my Turing email (shall I also do yours + @dcsw2 's turing emails?)

Yes, that would be great - maybe do my lancaster email just to be safe

**Comment by kmcdono2** [comment]
> Where to advertise:
> 
> * [ ]  DHSI listserv @kmcdono2
> * [ ]  DH French listserv @kmcdono2 
> * [ ]  CHR discourse @dcsw2
> * [ ]  scivision channel @rwood-97
> * [ ]  mapreader workspace @kmcdono2
> * [ ]  ask Dave for RSE comms @rwood-97
> * [ ]  lancaster DH list @kmcdono2
> * [ ]  N8 comms - ask Luca @kmcdono2
> * [ ]  ask Ruth to share at QM @dcsw2
> * [ ]  send to Chris @kmcdono2
> * [ ]  send to Xavier and Glenn, Carmen @kmcdono2
> * [ ]  bluesky @kmcdono2
> * [ ]  mastodon @dcsw2

@dcsw2 @ruthahnert @rwood-97 - I think we are ready for this phase! If @ruthahnert @DavidBeavan @fedenanni have ideas for other places to advertise, please let us know!
