### ISSUE TITLE
Think about using context model for training/fine-tuning model

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#287]
It would be good to test the 'context' version of MapReader.
 - Maybe first talk to Kapsar
 - Run some tests

**Comment by thobson88** [comment]
Notes on hackmd: https://hackmd.io/rJPX1LAJTsu5LFbdbW0YYg

**Comment by rwood-97** [comment]
From meeting (11/01/2023), plan is to try an alternative approach using context in post-processing rather than during training/classification.

Consider examples (X = railspace, o = no):

|  |  |  |
|---|---|---|
| o | o | o |
| o | X | o |
| o | o | o | 

^ This is likely a false positive

|  |  |  |
|---|---|---|
| o | o | o |
| X | X | X |
| o | o | o |

^ This is likely correct

|  |  |  |
|---|---|---|
| o | o | o |
| o | X | o |
| o | X | X |

^ This likely requires attention/review

This kind of post-processing can be done fairly easily using rules to pick out which ones we want to change labels for and/or review. 
See notes in hackmd for more info.

Things to consider: 
- How does this generalise across other MapReader use cases? e.g. non-linear features such as trees? Any post-processing that is included into MapReader code should allow users to define their own rules for false-positives etc. to allow for different use cases
