### ISSUE TITLE
small fixes in documentation side bar

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#289]
**Is your documentation update related to a problem? Please describe.**
Typos/standardizing text in side bar.

**Describe the solution you'd like**
- title case for all section headers (e.g. "Worked examples" should be "Worked Examples")
- add apostrophe for "Developers Guide" ("Developer's Guide")
- update "Classify" in User Guide to "Train"

@rwood-97 I can do this if you point me to the right file to edit! I looked and wasn't 100% sure.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rwood-97** [comment]
Have done this and tagged you for review :)
Section headers are pulled from the pages themselves so just had to change the page titles
