### ISSUE TITLE
`max_mean_pixel`, annotation interface

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#30]
In whole-plant images (side views),  the white frame has very high mean pixel RGB values. We now added `max_mean_pixel` to the annotation interface.

**Comment by kasra-hosseini** [comment]
@evangeline-corcoran Could you please close this if/when the issue with high mean pixel RGB values is solved?

**Comment by evangeline-corcoran** [comment]
New max_mean_pixel argument works and I can filter annotation batches so that they aren't inundated with white patches from the experiment apparatus
