### ISSUE TITLE
Add a page to the docs titled "Community Calls"

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#349]
> @rwood-97 - can we add a page to the docs titled "Community Calls" where there is a list of dates and the info on how to get the meeting invite?

_Originally posted by @kmcdono2 in https://github.com/Living-with-machines/MapReader/issues/284#issuecomment-1927064728_

**Comment by kmcdono2** [comment]
contents:

- blurb about what calls are
- how to get details via slack
- how to volunteer to show your MapReader work
- dates (w/info on any guests doing demos)

**Comment by kmcdono2** [comment]
done and decided to combine with events page (also now updated to contain Data/Culture workshop details): https://github.com/Living-with-machines/MapReader/blob/main/docs/source/Events.rst
