### ISSUE TITLE
MapReader and Binder

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#35]
@ChristinaLast What do you think if we have more than one Binder link? Does it make sense to have:

- [ ] Example for Maps
- [x] Example for Plant images

For the latter, we have a link now:

https://mybinder.org/v2/gh/Living-with-machines/MapReader/main?labpath=examples%2Fquick_start%2Fquick_start.ipynb

I just tested it, and it works, but I want to also add all the cells/codes of that notebook to CI.

Related issue: https://github.com/Living-with-machines/MapReader/issues/28

**Comment by ChristinaLast** [comment]
<img width="1142" alt="Screenshot 2022-03-22 at 16 14 28" src="https://user-images.githubusercontent.com/36204574/159525197-6d11d155-d6b2-4d14-97fa-e742fd75df13.png">
Getting this issue currently, I think this is a binder (nginx) issue?

**Comment by kasra-hosseini** [comment]
@ChristinaLast yes, I think so too.

**Comment by kasra-hosseini** [comment]
@ChristinaLast mybinder seems to be back up. I just tested the `quick_start` notebook.

**Comment by ChristinaLast** [comment]
ok same, thanks. sorry was in a meet with @kmcdono2 and I wanted to demo then and there!

**Comment by ChristinaLast** [comment]
> I just tested it, and it works, but I want to also add all the cells/codes of that notebook to CI.

Let me know about how to achieve this, quite interested + it will definitely be useful!

**Comment by kasra-hosseini** [comment]
Yes, it would be great to add all the cells/codes of that notebook to CI. I think there are different ways to do this. The simplest would be to do exactly that: move all the codes to a function here: https://github.com/Living-with-machines/MapReader/tree/main/tests

e.g., we can have a new file there: `test_plant_simple.py`. In that file, we can have:

```python
import pytest

def test_plant_simple():
    [...move all the codes/cells here...]
    # In the above lines and/or in the end, we add some tests, e.g.:
    assert number_of_patches == ...
    assert number_of_predictions == ...
```

The issue with this is that there is no link between `test_plant_simple.py` and `quick_start` notebook, but I think it should be good for what we need on MapReader? (Alternatively, we can use `nbdev` or `nbconvert`.)

**Comment by kmcdono2** [comment]
@ChristinaLast @kasra-hosseini - here is the start of user roles. What other information would be useful to include, if any?

#### Historian (or other domain) 
(or researcher from any domain with a question that information about historical landscapes can help answer)

"I want to search the visual contents of a large set of maps to help me answer a question about the past."

- MapReader can help you find instances of spatial phenomena in a collection of maps that is too large for you to 'close read/view'.
- MapReader creates output that you can link and analyze in relation to other geospatial datasets (e.g. census, gazetteers, toponyms in text corpora).

- Tutorial/binder link

#### Data scientist
"I have a map or other image collection that I would like to analyze at the patch level using the annotation and inference tools in MapReader."

- MapReader can be applied to non-cartographic datasets. For example, we have applied it to whole plant images (add link to the relevant `Use cases` section).

- There are lots of ways we would like to extend the functionality of MapReader, for maps and other images. 

- Tutorial/binder (maybe this is the plant images one?)

#### GLAM Professional
"I have a collection of maps that have been scanned and georeferenced. How can I use MapReader?"

- If your maps cannot be openly released, MapReader can be used to create derived data that can be shared publicly. The institution could create these datasets or individual researchers could create datasets specific to their research questions.

**Comment by ChristinaLast** [comment]
> Yes, it would be great to add all the cells/codes of that notebook to CI. I think there are different ways to do this. The simplest would be to do exactly that: move all the codes to a function here: https://github.com/Living-with-machines/MapReader/tree/main/tests
> 
> e.g., we can have a new file there: `test_plant_simple.py`. In that file, we can have:
> 
> ```python
> import pytest
> 
> def test_plant_simple():
>     [...move all the codes/cells here...]
>     # In the above lines and/or in the end, we add some tests, e.g.:
>     assert number_of_patches == ...
>     assert number_of_predictions == ...
> ```
> 
> The issue with this is that there is no link between `test_plant_simple.py` and `quick_start` notebook, but I think it should be good for what we need on MapReader? (Alternatively, we can use `nbdev` or `nbconvert`.)

Apologies, I'm picking up on this not, after a holiday! and also a week on my other project. There is also [`Doctest`](https://docs.python.org/3/library/doctest.html) and its extension for `jupyter notebooks` [`xdoctest`](https://xdoctest.readthedocs.io/en/latest/xdoc_with_jupyter.html#method-2-outside-the-notebook) which can test a python script/notebook containing docstrings with tests. It could be useful for readability if tests were included in docstrings within functions in the |"quickstart" notebooks, at least for more technical users. If we used this, we would have to figure out whether upon build we can run this during binder build.

**Comment by andrewphilipsmith** [comment]
Given the remaining task for this is map-related, I've given it the `maps` label.

**Comment by andrewphilipsmith** [comment]
This issues has been close, as we are no longer pursuing the Binder integration.
