### ISSUE TITLE
Test out huggingface OCR models in existing classifier

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#359]
Following from #358 . 
The first step in getting mapreader text spotting task set up is to have a go with existing OCR models, maybe on hugging face or pytorch.
From this, we can get geojson output w/text and polygon.
Then can figure out method for connecting polygons/text across patches.

**Comment by kmcdono2** [comment]
Try: https://huggingface.co/facebook/detr-resnet-50

**Comment by rwood-97** [comment]
Output using keras-ocr to detect on patches then join to parent image:

![Image](https://github.com/Living-with-machines/MapReader/assets/72076688/377bf9dd-a682-406d-a1a8-416923f79c98)

Potential idea for dealing with cases where edges of letters are cut off (e.g. below) would be to have some forced overlap between patches when running the text detection/recognition task in MapReader.
For example, if you choose to have 100 pixel patches, when you patchify you should create patch 0-0-100-100 and then have 10 pixel overlap so 90-90-190-190 and then 180-180-280-280 etc etc. This would a) make merging polygons at edges easier and b) hopefully ensure that text instances where the letter is cut off would be picked up in one or other patch.

![Image](https://github.com/Living-with-machines/MapReader/assets/72076688/10693bf6-8b7e-42a2-9ba8-16b2c5976765)

Next steps:
- [ ] How to merge polygons
- [ ] Think through this patch overlap set up and have a go

**Comment by kmcdono2** [comment]
Maybe look at https://arxiv.org/abs/2403.12895
