### ISSUE TITLE
Getting started with Maps Tutorial in Binder

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#36]
Opening an issue to capture our work creating a "maps-specific quickstart" in `binder`. This will document a usse case, research question and code implementation for a `MapReader` pipeline looking at historical maps! 🗺

Here are the resources you will need to get involved:
- we are capturing all the content for the binder-deployed notebook in this [`hackMD`](https://hackmd.io/@ChristinaLast/getting-started-with-maps-tutorial) 
- we are working on  deployable version on binder [here](https://hub.gke2.mybinder.org/user/living-with-machines-mapreader-4nfueymk/doc/tree/examples/quick_start_historian)

### Current tasks
- [x] @ChristinaLast to add code to predict `buildings` to `hackMD` with "quickstart" tutorial for maps.
  - [ ] @ChristinaLast to get pre-labelled building annotations, or dedicate time to labelling images for model trainins
 - [x] @kmcdono2 to capture explanations suitable for non-technical historian to run quickstars notebook

You may also find the new and improved [`README`](https://hackmd.io/bcffLmxHSnCQH8xQE4Eneg#Use-Cases) draft useful!

**Comment by ChristinaLast** [comment]
Working on branch [36/create-quickstart-maps-notebook](https://github.com/Living-with-machines/MapReader/tree/36/create-quickstart-maps-notebook)

**Comment by kmcdono2** [comment]
@ChristinaLast @dcsw2 I have added to the hackmd note for the binder text, including "TODO" items where I think there should be more. I intend to largely work on these myself, but the final list at the end of the note include a number of code todos that it would be great for @ChristinaLast to take a look at. 

also @ChristinaLast do we need to set up a chat about the building labels? I can talk you through what we have, and what we are planning in terms of documenting/publishing the data (this has just been delayed bc of the delayed publication of the paper).

**Comment by kasra-hosseini** [comment]
I removed `examples/quick_start_historian/quick_start.ipynb` (see https://github.com/Living-with-machines/MapReader/pull/38) as it is empty. I would suggest keeping WIP / empty stuff in a PR and emerge them after review.

**Comment by kmcdono2** [comment]
Superseded by Readthedocs and new worked examples.
