### ISSUE TITLE
ImportError on SheetDownloader - JOSS Review

### ISSUE THREAD

**Issue by PipGrylls** [Living-with-machines/MapReader#365]
Links: #6434

Cannot import SheetDownloader from mapreader

**To Reproduce**
1. Launch a jupyter notebook with the Python (mr_py) kernel as specified in install docs
2. Run `from mapreader import SheetDownloader`
3. See error
4. Run `import mapreader`
5. In next cell use `mapreader.` then tab to see possible items in the namespace
6. No SheetDownloader

**Expected behavior**
Sheetdownloader should be available `from mapreader` or the documentation updated to reflect its actutal location.

**Screenshots**
Full notebook:
![Screenshot 2024-03-05 at 10 01 33](https://github.com/Living-with-machines/MapReader/assets/22835635/a6937934-88c7-4986-8e8a-c7fc17e4b009)
Scrolling down in tab complete.
![Screenshot 2024-03-05 at 10 02 03](https://github.com/Living-with-machines/MapReader/assets/22835635/99ac1074-5fea-4af0-af50-d097c706e706)

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1
 - Installed via conda

**Comment by rwood-97** [comment]
Hi, can you check which MapReader version this is? I think the conda install is outdated so won't have the `SheetDownloader` class?

**Comment by PipGrylls** [comment]
Conda:
python 3.8.18 h2469fbe_0_cpython conda-forge
mapreader 0.3.4+200.g542eca2 py38_0 anothersmith


If this is not up to date then it should be removed from the docs. Also the mixing of conda and pip/pypi becomes more of an issue.
