### ISSUE TITLE
patch bounding box as part of output file

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#37]
Request to include bounding box coordinates for each patch in MapReader output (e.g. in addition to patch centroid).

**Comment by kmcdono2** [comment]
As part of work that @andrewphilipsmith has been doing to reconstruct this for the StopsGB eval, we are aware it would be better for this to be built into the way we generate output from MapReader.

See https://github.com/Living-with-machines/MapReader/pull/29 

Decide when/how to do this in prep for next work iteration in LwM. To discuss at next MapReader working group meeting after Easter,

**Comment by kmcdono2** [comment]
@andrewphilipsmith I don't think this is maps specific

**Comment by rwood-97** [comment]
Have added saving patches as geotiffs (does this count as fixing this?) - see PR #163

**Comment by rwood-97** [comment]
@kmcdono2 is this done with geotiffs as patches?
