### ISSUE TITLE
Get text on maps gold standard annotations

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#375]
- [x] @kmcdono2 to send to @rwood-97

**Comment by kmcdono2** [comment]
when you've signed up for Recogito, let me know your user name

**Comment by kmcdono2** [comment]
I added you as a collaborator on Recogito. So you should see the OS maps that have gold standard annotations in your "Documents" list.

Basic info about 
- using Recogito
- annotating maps
is here: https://github.com/machines-reading-maps/Tutorials-Newsletters/wiki

Once you select a map (double click on the title), you can select "Download" options and export as JSON-LD, Geojson, etc.

![Image](https://github.com/Living-with-machines/MapReader/assets/20363927/8f919120-9537-4cc0-863c-051caacbeb54)

**Comment by kmcdono2** [comment]
done I think @rwood-97
