### ISSUE TITLE
Prepare for 2 day workshop

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#376]
For workshop on April 30th- May 1st

- [x] @kmcdono2 to make outline
- [x] set up meeting to discuss plan

**Comment by kmcdono2** [comment]
@kmcdono2 and @rwood-97 met on 8 April to redo schedule from June 2023 for April 2024 workshop.

Next steps:
- [ ] finish plan for May 1 (day 2) afternoon, which will be focused on using data
- [ ] check if Kaspar or Josh can join (and maybe Guy?)
- [ ] check about consulting fees for them w/Ruth & Laura
- [ ] go through slides and reorganize/update based on new schedule
- [ ] find out if new RAM can attend and what they might want to do (reasonably, as part of onboarding)
- [ ] prepare email for participants that includes brief survey and instructions for what to do in advance

**Comment by rwood-97** [comment]
https://docs.google.com/document/d/1ptY1dw_qxgIVKG7lz-bh3uG-mz0GRQ2FaEgJmPok-cg/edit#heading=h.oehoktacw2ki

**Comment by rwood-97** [comment]
- [ ] slides
- [ ] fix timings
- [ ] David Alexander bits for visualisation

**Comment by kmcdono2** [comment]
Work with David on using data for June workshop.
