### ISSUE TITLE
consider challenge for Fine-Grained Visual Categorization in 2024

### ISSUE THREAD

**Issue by kmcdono2** [Living-with-machines/MapReader#387]
FCVC11 site - https://sites.google.com/view/fgvc11/home?authuser=0 

About:

> Workshop Overview
> It may be tempting to think that image classification is a solved problem. However, one only needs to look at the poor performance of existing techniques in domains with limited training data and highly similar categories to see that this is not the case. In particular, fine-grained categorization, e.g., the precise differentiation between similar plant or animal species, disease of the retina, architectural styles, etc., is an extremely challenging problem, pushing the limits of both human and machine performance. In these domains, expert knowledge is typically required, and the question that must be addressed is how we can develop artificial systems that can efficiently discriminate between large numbers of highly similar visual concepts. 
> 
> 
> The 11th Workshop on Fine-Grained Visual Categorization (FGVC11) will explore topics related to supervised learning, self-supervised learning, semi-supervised learning, vision and language, matching, localization, domain adaptation, transfer learning, few-shot learning, machine teaching, multimodal learning (e.g., audio and video), 3D-vision, crowd-sourcing, image captioning and generation, out-of-distribution detection, anomaly detection, open-set recognition, human-in-the-loop learning, and taxonomic prediction, all through the lens of fine-grained understanding. Hence, the relevant topics are neither restricted to vision nor categorization. 
> 
> 
> Our workshop is structured around five main components: 
> 
> (i) invited talks from world-renowned computer vision experts, 
> 
> (ii) invited talks from experts in application domains (e.g., medical science and ecology), 
> 
> (iii) interactive discussions during poster and panel sessions, 
> 
> (iv) novel fine-grained challenges that are hosted as part of the workshop, and 
> 
> (v) peer-reviewed extended abstract paper submissions. 
> 
> 
> We aim to stimulate debate and to expose the wider computer vision community to new and challenging problems in areas that have the potential for large societal impact but do not traditionally receive a significant amount of exposure at other CVPR workshops.

**Comment by kallewesterling** [comment]
This is too late now, and I will close this issue.
