### ISSUE TITLE
Suggestion for Conda install instructions

### ISSUE THREAD

**Issue by Cyara-she-her** [Living-with-machines/MapReader#402]
**Is your documentation update related to a problem? Please describe.**
(written by @phinate on behalf of @cyara-she-her): when installing Conda, we need to also install Python! Doing
```
conda create -n mapreader
conda activate mapreader
```
will not configure Python, so we had to install Python etc separately. 

**Describe the solution you'd like**
Changed instructions to something like
```
conda create -n mapreader python
...
```
to make sure `python`  points to the right instance of Python.

**Comment by rwood-97** [comment]
I had no idea this was a thing so thanks for flagging! is now fixed in the docs :)
