### ISSUE TITLE
Update annotated_images.show_sample() example

### ISSUE THREAD

**Issue by rxcoulton** [Living-with-machines/MapReader#406]
**Is your documentation update related to a problem? Please describe.**
Example in docs is wrong: https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Train.html

**Describe the solution you'd like**
correct .show_image_labels() code snipped to .show_sample()

**Describe alternatives you've considered**

**Additional context**
discussed with Rosie during the training session

**Comment by rwood-97** [comment]
Thanks, will add this as part of #417
