### ISSUE TITLE
show metadata (e.g pixel values, geometry) in the annotator view

### ISSUE THREAD

**Issue by sparkyc84** [Living-with-machines/MapReader#407]
When annotating sometimes one doesn't set good min/max/filter values and so patches to label can be few and far between.  This increases the amount of time it takes to get a good number of annotations.

It would be useful to be able to see patch metadata when annotating - this would provide hints to help set the min_values and max_values in the Annotator object constructor.  Maybe this could be something toggled on/off via a property passed when setting up the Annotator.

**Comment by kallewesterling** [comment]
Thank you @sparkyc84 for this great suggestion. We'll have a look at it as a potential future feature added! If you're interested, we have [Community Calls](https://mapreader.readthedocs.io/en/latest/Events.html) for the MapReader package, and I wanted to highlight that [our upcoming community call, August 1 at 4pm UK time](https://docs.google.com/document/d/1UE2OjPE7OitoB8AsG4swk1k3pD44lW_YgMkaR4VxUXU/edit), will focus on coming up with future potential features and a roadmap for MapReader ahead. Would you be interested in joining?

**Comment by sparkyc84** [comment]
@kallewesterling thanks! I'd love to join but unfortunately I am away that week.  I'd be interested in participating in future though :-)

**Comment by kallewesterling** [comment]
@sparkyc84 The sign-up is actually open for September 5, 2024, 4-5pm (BST) as well: https://forms.office.com/e/x9zGL0yQyp
