### ISSUE TITLE
Broken URL in the Workshop_AprilMay2024_part2.ipynb notebook

### ISSUE THREAD

**Issue by ludovicmoncla** [Living-with-machines/MapReader#408]
The URL to the `Classify` documentation webpage is broken in the `Create datasets and dataloaders` subsection.
This link https://mapreader.readthedocs.io/en/latest/User-guide/Classify.html#prepare-datasets-and-dataloaders
needs to be replaced by 
https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Train.html

**Comment by rwood-97** [comment]
Will add to #417
