### ISSUE TITLE
Invalid syntax error on the calculate_add_metrics cell

### ISSUE THREAD

**Issue by ludovicmoncla** [Living-with-machines/MapReader#409]
There is a syntax error in the following cell: 

```python
#EXAMPLE
my_classifier.calculate_add_metrics(a
    y_true=my_classifier.orig_label,
    y_pred=my_classifier.pred_label,
    y_score=my_classifier.pred_conf,
    phase="test",
)
```
found in this page: https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Train.html#testing 
The `a` must be removed after the parenthesis.

**Comment by rwood-97** [comment]
Will add to #417
