### ISSUE TITLE
Displaying scores per class

### ISSUE THREAD

**Issue by ludovicmoncla** [Living-with-machines/MapReader#410]
For those using multiclass classification, it would be interesting if you add an example in the documentation to display the scores per class. This can be very useful, especially for unbalanced datasets.
For instance, for displaying fscore on the test set:
```python
for label_id, label_name in annotated_images.labels_map.items():
    print(label_name, my_classifier.metrics['epoch_fscore_'+str(label_id)+'_test'])
```
I suggest adding this before the `Saving your work` section: https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Train.html#saving-your-work

**Comment by kmcdono2** [comment]
Thanks @ludovicmoncla - we'll add this!

**Comment by rwood-97** [comment]
Part of #417
