### ISSUE TITLE
Add the device argument for GPU support on the ClassifierContainer()

### ISSUE THREAD

**Issue by ludovicmoncla** [Living-with-machines/MapReader#411]
I would suggest adding the device argument in the ClassifierContainer() constructor in the documentation (and also in the Workshop_AprilMay2024.ipynb notebook): 
https://mapreader.readthedocs.io/en/latest/User-guide/Classify/Infer.html#initialize-classifiercontainer
for support for GPU: Nvidia chips (`cuda`) or Apple Mx chips (`mps`).

```python 
import torch

my_model = torch.load("./models/model_checkpoint_6.pkl")
labels_map = {0: "no_railspace", 1: "railspace"}
device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'

my_classifier = ClassifierContainer(my_model, labels_map, device=device)
```

For instance, running the inference example from the Workshop_AprilMay2024.ipynb notebook on a M1 Max Macbook laptop, the difference is 20 sec using GPU support against 9 min on CPU.

**Comment by rwood-97** [comment]
Thanks, I will add this as part of the work in ticket #417
