### ISSUE TITLE
Can't download maps using my_ts.download_map_sheets_by_queries()

### ISSUE THREAD

**Issue by rxcoulton** [Living-with-machines/MapReader#412]
<img width="1000" alt="map_101427849" src="https://github.com/Living-with-machines/MapReader/assets/40853725/d06bf3c1-5427-473c-8db2-1e916120217b">
**Describe the bug**
Using MapReader in the Data/Culture workshop. Trying to download a set of maps and metadata for 32 x 6-inch OS maps that I had selected using a within-polygon based query.

**To Reproduce**

Following the steps in the ipynb Part 1, I ran: 

```
my_polygon = create_polygon_from_latlons(51.59, -0.06, 51.50, 0.18)
my_ts.query_map_sheets_by_polygon(my_polygon, mode="intersects", print=True, append=True)
my_ts.get_grid_bb(14)
my_ts.download_map_sheets_by_queries()
```

(At least I think these are all the key steps -- I'm confident the query results were queued up ready to download.)

On first attempt the first few maps downloaded (approx 12/32). The 13th map half-downloaded with pixellated right-hand side (see attached). The first 12/32 lines were written to the ``. No further maps downloaded but versions of this error message printed:

```
Image has missing tiles in bottom left corner.
Image has missing tiles in upper right corner.
[WARNING] Download of "map_96804981.png" was unsuccessful.
Image has missing tiles in bottom left corner.
Image has missing tiles in upper right corner.
Image has missing tiles in bottom left corner.
Image has missing tiles in upper right corner.
[WARNING] Download of "map_96804987.png" was unsuccessful.
[WARNING] Download of "map_96804990.png" was unsuccessful.

```
**Expected behavior**
Expected the maps slowly to download from the server into my `maps` directory with a `metadata.csv`

**Screenshots**

Attached.
<img width="910" alt="Screenshot 2024-05-01 154508" src="https://github.com/Living-with-machines/MapReader/assets/40853725/8fc29837-972f-43d0-a561-54f5bcc6b12c">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 11

**Additional context**
another user was experiencing the same issue -- presume it is upstream / server-side

**Comment by rwood-97** [comment]
Hi, I think this was potentially due to the Turing IP getting blocked during the workshop as we'd made too many requests.
The code looks okay so hopefully this should work if you run it again now.
