### ISSUE TITLE
Add a warning of how many GB of data downloading will generate

### ISSUE THREAD

**Issue by rwood-97** [Living-with-machines/MapReader#444]
**Describe the solution you'd like**
At the moment, users can download all map sheets from a series if they like but this could generate hundreds of GBs of data. 
We should add a warning/info message to say approximately how much data it is likely to create before downloading. Maybe with a user input to say confirm and a `force` argument for if it is used as part of a script.

How this would work:
- work out how many MB 1 tile is
- work out how many tiles it is in total (I think this is possible from `GridBoundingBox`)
- calculate total size of requested download

**Comment by kallewesterling** [comment]
I think using a HEAD request, you can get `Content-Length` from the response, and then tell the user the size... 🤔

**Comment by kallewesterling** [comment]
![image](https://github.com/Living-with-machines/MapReader/assets/7298727/957c627d-4090-41b8-9561-aabbf5924eaa)

Looks like this works:

```py
h = requests.head("https://geo.nls.uk/maps/os/1inch_2nd_ed/9/255/168.png")
if "Content-Length" in h.headers.keys():
    print(h.headers["Content-Length"])
```

**Comment by kallewesterling** [comment]
@rwood-97 It does seem like `Content-Length` is not guaranteed in `HEAD` responses, however... So we might want a backup option that kicks in if the `HEAD` request doesn't actually return good data..

**Comment by rwood-97** [comment]
What seems like a good threshold for too much data? I'm thinking we do
```
if total_size > xxxx:
   continue
else:
   raise warning and you'll need to add a `force` argument to make it bypass this
```
