### ISSUE TITLE
Issue with SpotText documentation

### ISSUE THREAD

**Issue by BWoody711** [Living-with-machines/MapReader#479]
Hi all, 

I was following along with the MapReader 1.3.4 documentation on my Windows 11 machine and was trying to get SpotText to work. Initially, I copied and pasted the code block below, and it was unable to import DeepSoloRunner. However, after trying several solutions, I changed the import statement to "from mapreader.spot_text.deepsolo_runner import DeepSoloRunner" and things now seem to be working fine. I am wondering if this is an issue with how I set up mapreader, or if this should be updated in the documentation to avoid confusion in the future.

Kind regards,

Ben

---

from map_reader.spot_text import DeepSoloRunner

my_runner = DeepSoloRunner(
    patch_df,
    parent_df,
    cfg_file = "DeepSolo/configs/R_50/IC15/finetune_150k_tt_mlt_13_15_textocr.yaml",
    weights_file = "./ic15_res50_finetune_synth-tt-mlt-13-15-textocr.pth"
)

**Comment by rwood-97** [comment]
Hi,

Thanks for flagging this. Coincidentally, I also noticed this last week and have changed it in #474 . This should be merged soon so should fix the issue.

`from mapreader.spot_text.deepsolo_runner import DeepSoloRunner` or `from mapreader import DeepSoloRunner` should both work.

**Comment by rwood-97** [comment]
Think this is fixed now :)
