### ISSUE TITLE
Check MapReader installation + test notebooks

### ISSUE THREAD

**Issue by kasra-hosseini** [Living-with-machines/MapReader#49]
Installation: https://github.com/Living-with-machines/MapReader#installation
Notebooks: https://github.com/Living-with-machines/MapReader#use-cases

**Comment by dcsw2** [comment]
Sure, will do this, but probably next week as we have our workshop tomorrow and a million delayed tasks for Friday...

**Comment by kasra-hosseini** [comment]
@dcsw2 Thanks! Next week is good :)

**Comment by kasra-hosseini** [comment]
@kmcdono2 @dcsw2 any updates on this?

**Comment by kmcdono2** [comment]
I was able to install fine using after using pip3 instead of pip. There was a dependency error with rasterio/click.

some quick comments:
- include note to try pip3 in mac/linux install
- right now "use cases", "tutorials", and "examples" are used a bit interchangeable in the README and in the directory structure. I would streamline this, or at least claridy that there are "examples" of "use cases". Saying there are also tutorials makes it confusing (are the tutorials the same as the examples? we all know that they are, but a new person does not).

re: notebooks: My kernel keeps dying. Is this a problem with the env? I used the line of code for enabling `mrpy_38` in the notebooks, but something is definitely wrong.

**Comment by kmcdono2** [comment]
@kasra-hosseini I removed everything to give it a 2nd go, and used pip install. Now, I cannot access the notebooks. When it use `pip install mapreader,` and then open jupyter, I have no idea where the notebooks are. Can you advise?

**Comment by kasra-hosseini** [comment]
> * right now "use cases", "tutorials", and "examples" are used a bit interchangeable in the README and in the directory structure. I would streamline this, or at least claridy that there are "examples" of "use cases". Saying there are also tutorials makes it confusing (are the tutorials the same as the examples? we all know that they are, but a new person does not).

@kmcdono2 please open a PR for this. Thanks.

**Comment by kasra-hosseini** [comment]
> re: notebooks: My kernel keeps dying. Is this a problem with the env? I used the line of code for enabling `mrpy_38` in the notebooks, but something is definitely wrong.

Do you still have this problem? if yes, could you please send me a screenshot of the terminal (where you opened the jupyter notebook)?

**Comment by kasra-hosseini** [comment]
> * include note to try pip3 in mac/linux install

Done

**Comment by kasra-hosseini** [comment]
> @kasra-hosseini I removed everything to give it a 2nd go, and used pip install. Now, I cannot access the notebooks. When it use `pip install mapreader,` and then open jupyter, I have no idea where the notebooks are. Can you advise?

You still need to download/clone the repo to access the notebooks.

**Comment by kasra-hosseini** [comment]
> Hi Kasra,
> I got as far as the instruction at line 120 (to allow the notebooks to show up in the environment) but they don't show up and I can't find them anywhere locally.

I think this is the same issue as?

> @kasra-hosseini I removed everything to give it a 2nd go, and used pip install. Now, I cannot access the notebooks. When it use pip install mapreader, and then open jupyter, I have no idea where the notebooks are. Can you advise?

Please note that `pip3 install mapreader` only installs the library. It does not download the example notebooks. To access those, you need to download/clone the repo. I updated the README to emphasize this.

**Comment by kmcdono2** [comment]
@kasra-hosseini I will make some additional comments about install instructions in a PR and will connect with @andrewphilipsmith and @dcsw2 about this.

**Comment by andrewphilipsmith** [comment]
In discussion with @kmcdono2;

Things to check:

- [ ] Does the installation work correctly? eg do the dependencies get installed correctly and can run `import mapreader`.
- [ ] Is the installation process explained suitably in the readme.md?
- [ ] Does the installation enable to completion of the "geospatial" notebook.
- [ ] Does the installation enable to completion of the "non-geospatial" notebook.
- [ ] Does the installation enable to completion of the "quick-start" notebook.
- [ ] Confirm that we *don't* need to test the "postproc" notebook, as that does not directly use the mapreader libary.

**Comment by kmcdono2** [comment]
@rwood-97 has reviewed all the notebooks and new tickets supercede this, so closing
