### ISSUE TITLE
🐛 `LoadAnnotations` not returning annotation interface

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#51]
When using a local notebook to run through the annotation section of the `quick_start` notebook, I am unable to see the `LoadAnnonations` object returned in order to generate new labels! See screen shot below:

![Screenshot 2022-05-09 at 13 58 51](https://user-images.githubusercontent.com/36204574/167415311-b874b5bb-b3d0-4f26-8780-ec2b3e0c15ea.png)

**Comment by kasra-hosseini** [comment]
@ChristinaLast in the current version of `quick_start`, we skip the annotation step. We load an existing `csv` file. Could you please check `002_annotation` notebook here: 

- https://github.com/Living-with-machines/MapReader/tree/main/examples/geospatial/classification_one_inch_maps_001
- https://github.com/Living-with-machines/MapReader/tree/main/examples/non-geospatial/classification_plant_phenotype

**Comment by kasra-hosseini** [comment]
(`annotated_images = loadAnnotations()` loads an existing CSV file. `prepare_annotation` in `002_annotation` notebook is used for annotating new patches/images.)

**Comment by kasra-hosseini** [comment]
I close this as the output reported above is expected. @ChristinaLast please re-open if there are any issues with the `prepare_annotation` function.
