### ISSUE TITLE
Publish as a conda package

### ISSUE THREAD

**Issue by andrewphilipsmith** [Living-with-machines/MapReader#73]
**Is your feature request related to a problem? Please describe.**
Some of the dependencies are much easier to install using conda than using pip. We also recommend that users install MapReader in a conda environment. Mixing conda installs and pip installs is known to be problematic.

**Describe the solution you'd like**
Publish MapReader as a conda package, eliminating the need to mix conda installs and pip installs.

**Comment by kallewesterling** [comment]
Pending PR merge https://github.com/Living-with-machines/MapReader/pull/74
