### ISSUE TITLE
`annotation` function in `002_annotation.ipynb` freezes on same patch after 99 annotations

### ISSUE THREAD

**Issue by ChristinaLast** [Living-with-machines/MapReader#9]
Testing `annotation` function (works really well!) up until 99 annotations, at which point it freezes on the same patch.

![Screenshot 2021-12-01 at 11 30 47](https://user-images.githubusercontent.com/36204574/144227097-98ed5d2e-357a-490a-b028-aa06dc98857c.png)

**Comment by kasra-hosseini** [comment]
@ChristinaLast Many thanks for testing this 🙏 . It is very helpful. So we do the annotations in batches of 100. After one batch is finished, we need to save them locally (next cell), and then restart a new batch. MapReader first checks the existing annotations and only shows the remaining patches to be annotated.

However, I see that maybe it would be better to give the option to the user to select the batch size in the annotation interface. I created an issue for this: https://github.com/Living-with-machines/MapReader/issues/10

**Comment by kmcdono2** [comment]
Happening in #10
